### ISSUE TITLE
Make step-items clickable

### ISSUE THREAD

**Issue by tsilcher** [Wikiki/bulma-steps#11]
Hi, I'd like to suggest an enhancement feature and have `step-item`'s clickable in order to be able to select manually the step by clicking on it. (e.g. Click on "**Step 4**" and switch directly to it).

Thanks.

**Comment by tsilcher** [comment]
Any update on this?

**Comment by Wikiki** [comment]
Hi,

Not yet sorry. I'm a little bit jusy these days. I'll try to add it before the end of the week.

**Comment by socunanena** [comment]
Hello, is this feature already implemented? I tried to use the `stepClickable` option but it doesn't really work. Browsing the code it seems that it's not finished. Is there any plan to implement it?

Many thanks!

**Comment by Wikiki** [comment]
Hi,

it's in the ToDo but no release date planed

**Comment by aman54kumar** [comment]
Hi, any updates on this? It's been almost 1 year since last update and no word in the documentation for it atleast.
