### ISSUE TITLE
JavaScript Example

### ISSUE THREAD

**Issue by felixerdy** [Wikiki/bulma-steps#12]
Could you please provide a JavaScript example code?

I am using your HTML snippet from [here](https://wikiki.github.io/components/steps/#javascript) and tried to instantiate steps with the following JS code:
```javascript
let steps = new bulmaSteps('#stepsDemo', {
    onShow: (id) => console.log(id)
})
```

Unfortunately, I get the following error: `Uncaught TypeError: a.querySelectorAll is not a function`

**Comment by felixerdy** [comment]
Okay, I just found the solution by myself:
```
new bulmaSteps(document.getElementById('stepsDemo'), {
    onShow: (id) => console.log(id)
})
```

**Comment by AngelTorres96** [comment]
@felixerdy Hi, could you please explain me how it works this line? onShow:(id)=>console.log(id), i don't understand the id parameter
