### ISSUE TITLE
Problem with Undefined Variable

### ISSUE THREAD

**Issue by chobo2** [Wikiki/bulma-steps#14]
I try to do in my reactjs/webpack project

import "../../node_modules/bulma/bulma.sass";
import "../../node_modules/bulma-steps/dist/bulma-steps.sass";

I get: Undefined variable: "$grey-light".

**Comment by chobo2** [comment]
hmm yea that is what I thought but I am importing everything in. So I am not sure why it is not happening.

**Comment by Wikiki** [comment]
can you access to any other bulma variables within your source (without importing my extension) ?

**Comment by chobo2** [comment]
I am not sure. I am importing bulma into my component not through another sass file.

**Comment by Wikiki** [comment]
can you then try to create a custom sass file using a bulma's variable and import it before the extension to check ?

**Comment by chobo2** [comment]
Yea if I create a custom sass file and put both the bulmas sass files in it works perfectly fine. I guess it can't work with components and webpack.

**Comment by Wikiki** [comment]
<code>is-success</code> is the bulma color modifier. That's why I use <code>is-completed</code> to manage completed tasks

**Comment by chobo2** [comment]
when you say `is-completed` is to manage completed tasks. Do you mean it has no effect on styling but is used for the javascript?

I am bit confused if `is-active, is-completed` change the styling.

**Comment by Wikiki** [comment]
is-active is to style the current active step. is-completed is to style a finished steps. and finallt is-success is just as is-danger, is-warning,....it's just to force the default step color

**Comment by Wikiki** [comment]
is-completed is used both by sass and JavaScript
