### ISSUE TITLE
onFinish never called

### ISSUE THREAD

**Issue by helmi77** [Wikiki/bulma-steps#17]
Correct me if I'm wrong, but as far as I understand it `onFinish` will never get called. If you consider [this line](https://github.com/Wikiki/bulma-steps/blob/e757fcfb1a6fa24bbd20c38f089903ae8fe2adf3/src/js/index.js#L192) in `index.js` it compares the `next_id` with the number of steps and only triggers `onFinish` when the `next_id` is equal to the step count.

I thought `onFinish` would be called when you are on the second to last step and proceed to the last step. The problem is, since `next_id` is zero-based and the step length is not, when you're at the `(n - 1)`st step this line will never evaluate to true, since you're comparing against `n`.

**Comment by yassinelazaar** [comment]
Just a reminder that this fix didn't made it to 2.2.1.

**Comment by rahadi** [comment]
@yacinelazaar do you know which version has this change? I couldn't find it.
