### ISSUE TITLE
attach is not a function error

### ISSUE THREAD

**Issue by tqiqbal** [Wikiki/bulma-steps#19]
Hi, I am getting error while invoking function bulmaSteps.attach(selector, options). I am using VueJs+webpack . I have done these steps.

Imported bulma.css
imported bulma-steps.min.css
imported bulms-steps.min.js
called bulmaSteps.attach(selector, options)
In Chrome console I can see this error.

"Task.vue?8a51:152 Uncaught TypeError: __WEBPACK_IMPORTED_MODULE_0_bulma_extensions_bulma_steps_dist_bulma_steps_min_js___default.a.attach is not a function
at eval (Task.vue?8a51:152)
at Object../node_modules/babel-loader/lib/index.js!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/components/pages/Task.vue (app.js:790)
at webpack_require (app.js:679)
at fn (app.js:89)
at eval (Task.vue?bf53:1)
at Object../src/components/pages/Task.vue (app.js:1422)
at webpack_require (app.js:679)
at fn (app.js:89)
at eval (index.js?3672:1)
at Object../src/router/index.js (app.js:1518)"

Note: I am new to Bulma ( and its extensions) and VueJS

Regards,
Tanveer

**Comment by Wikiki** [comment]
Hi,

do you still having the issue with the last release ?

**Comment by tanacute** [comment]
Hi,

I had installed bulma-steps (1.0.3) through npm bulma-extensions(1.0.32).

Rg,
Tanveer

**Comment by Wikiki** [comment]
please try bulma-extensions v2.2.1

**Comment by iqbalt** [comment]
Thanks, Error is gone. Great work for new version. However I am still unable to navigate through. 

here how I did in my Vue Component.

"import bulmaSteps from 'bulma-extensions/bulma-steps/dist/js/bulma-steps.js';
bulmaSteps.attach();"

Nothing is happening.

**Comment by RiFi2k** [comment]
If someone else is having problems using with Vue, you want to run the attach method in the mounted hook. If you do it there it works perfectly.

https://vuejs.org/v2/guide/components-edge-cases.html#Programmatic-Event-Listeners
