### ISSUE TITLE
Symbol" is not defined & BulmaSteps is not defined - IE11 (EDGE)

### ISSUE THREAD

**Issue by alvisecastagna1** [Wikiki/bulma-steps#23]
Only in Internet Explorer the step doesn't work, I have the following 2 console error: 

"Symbol" is not defined" on bulma-steps-min-js

and below: 

"BulmaSteps is not define"
bulma = new bulmaSteps(document.getElementById("stepsForm"), {});

There are any fix to IE? 

Thanks,

**Comment by Wikiki** [comment]
Hi,

maybe you can use the polyfill:
```html
<script src="https://cdnjs.cloudflare.com/ajax/libs/babel-core/5.6.15/browser-polyfill.min.js"></script>
```

**Comment by alvisecastagna1** [comment]
Hi, 
Thanks work now!
