### ISSUE TITLE
Module build failed

### ISSUE THREAD

**Issue by gfelot** [Wikiki/bulma-steps#5]
Trying to add this extension in a NUXT project.

I got the error : 
```
Module build failed: Unexpected format /Users/Gil/Code/Galinette/SSRWebSite/node_modules/bulma/sass/extensions/_all.sass a (2:0)

  1 | /*! bulma.io v0.6.0 | MIT License | github.com/jgthms/bulma */
> 2 | @import /Users/Gil/Code/Galinette/SSRWebSite/node_modules/bulma/sass/extensions/_all.sass a;
  3 | @keyframes spinAround {
  4 |   from {
  5 |     transform: rotate(0deg); }


 @ ./node_modules/bulma/bulma.sass 4:14-152 13:3-17:5 14:22-160
 @ ./node_modules/babel-loader/lib?{"babelrc":false,"cacheDirectory":true,"presets":["/Users/Gil/Code/Galinette/SSRWebSite/node_modules/babel-preset-vue-app/dist/index.common.js"]}!./node_modules/vue-loader/lib/selector.js?type=script&index=0&bustCache!./.nuxt/App.vue
 @ ./.nuxt/App.vue
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi webpack-hot-middleware/client?name=client&reload=true&timeout=3000&path=/__webpack_hmr ./.nuxt/client.js
```

I follow the steps by add the .sass file to a `extensions` folder then importing a `_all.sass`.

Any idea what's wrong ?

**Comment by gfelot** [comment]
My bad I add a sneaky char hiding where it shouldn't be !

**Comment by Wikiki** [comment]
Hi,

If you still facing the issue, maybe you should remove "<space>a" at the end of the import rule;

Regards

**Comment by gfelot** [comment]
Do I have to do extra steps to integrate this extension because I don't have like in the 1st example. 
<img width="563" alt="screen shot 2017-10-23 at 11 20 50" src="https://user-images.githubusercontent.com/7879555/31881583-4e5dd30a-b7e4-11e7-9196-1880febf4534.png">

**Comment by Wikiki** [comment]
No, you don't.

Are you sure the rules are well intergated to your final code (by cheking with the browser console) ?

**Comment by gfelot** [comment]
Don't see the rules nope.
Just copy and past the sass file.
<img width="273" alt="screen shot 2017-10-23 at 11 39 47" src="https://user-images.githubusercontent.com/7879555/31882371-e5faf7a4-b7e6-11e7-96c7-af5936b51887.png">

**Comment by Wikiki** [comment]
Did you update bulma.sass to import the new _all.sass file ?

**Comment by gfelot** [comment]
Inside `bulma.sass` I added : `
@import "sass/extensions/_all"`
And inside `nuxt.config.js` i added : 
```
 css: [
    { src: 'bulma/bulma.sass', lang: 'sass' },
    { src: 'font-awesome/scss/font-awesome.scss', lang: 'scss' }
  ]
```

Bulma itself working well (using columns/card/media [...]).

**Comment by Wikiki** [comment]
Normally import inside bulma.sass enough to do the job.
Are you able to share your code ?

**Comment by gfelot** [comment]
Just made a temp repository with the node_modules included.

Thanks

https://github.com/gfelot/WebSiteNUXT

**Comment by Wikiki** [comment]
Hi,

I've fixed the issue in your project and made a PR on your temp repository.

Regards

**Comment by gfelot** [comment]
Nice... working like a charm !

**Comment by Wikiki** [comment]
You're welcome.
